export type TCandidate = {
  id: number;
  vacancyID: number;
  nomeCompleto: string;
  email: string;
  telefone: string;
  dataNasc: string;
  cpf: string;
  cargo: string;
  empresa: string;
  dataInicioEmpresa: string;
  dataTerminoEmpresa: string;
  descricaoATVD: string;
  situacao: string;
  escolaridade: string;
  curso: string;
  instituicao: string;
  dataInicioEstudo: string;
  dataTerminoEstudos: string;
};
